/**
 * Template loader with filesystem-first, embedded-fallback strategy.
 *
 * Filesystem path: used when templates ship alongside the package
 * (npm/npx/bunx install + dev workflow).
 *
 * Embedded fallback: used when running as a `bun --compile` single binary
 * where templates/ is not on disk. Constants come from `embedded.ts`,
 * regenerated by `scripts/embed-templates.ts` whenever templates change.
 */

import { readFile } from 'fs/promises';
import * as path from 'path';
import { EMBEDDED_TEMPLATES, type EmbeddedTemplateName } from './embedded.js';

export type TemplateName = EmbeddedTemplateName;

/**
 * Load a template by filename. If `templateDir` is provided and contains the
 * file, returns its filesystem content. Otherwise falls back to the embedded
 * constant.
 */
export async function loadTemplate(
  name: TemplateName,
  templateDir?: string
): Promise<string> {
  if (templateDir) {
    const fsPath = path.join(templateDir, name);
    try {
      return await readFile(fsPath, 'utf-8');
    } catch (err: unknown) {
      const code = (err as NodeJS.ErrnoException)?.code;
      if (code !== 'ENOENT' && code !== 'ENOTDIR') {
        throw err;
      }
    }
  }
  return EMBEDDED_TEMPLATES[name];
}
