/**
 * Generate src/cli/templates/embedded.ts from templates/* files.
 *
 * Templates ship two ways:
 *   1. As loose files under `templates/` (npm/npx/bunx install) — preferred path
 *   2. Embedded as string constants in the binary (bun --compile distribution)
 *
 * This script regenerates the embedded constants whenever templates change.
 * Run via `npm run embed-templates` (wired into prebuild).
 */

import { readFile, writeFile, readdir } from 'fs/promises';
import { fileURLToPath } from 'url';
import * as path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = path.resolve(__dirname, '..', 'templates');
const OUTPUT_PATH = path.resolve(__dirname, '..', 'src', 'cli', 'templates', 'embedded.ts');

async function main(): Promise<void> {
  const files = await readdir(TEMPLATES_DIR);
  const entries: Array<[string, string]> = [];

  for (const filename of files.sort()) {
    const filePath = path.join(TEMPLATES_DIR, filename);
    const content = await readFile(filePath, 'utf-8');
    entries.push([filename, content]);
  }

  const lines: string[] = [
    '/**',
    ' * Auto-generated by scripts/embed-templates.ts. Do not edit by hand.',
    ' *',
    ' * Templates embedded as string constants for the bun --compile single-binary',
    ' * distribution where templates/ is not on disk. The filesystem path is',
    ' * preferred when available (npm install).',
    ' */',
    '',
    'export const EMBEDDED_TEMPLATES = {',
  ];

  for (const [name, content] of entries) {
    lines.push(`  ${JSON.stringify(name)}: ${JSON.stringify(content)},`);
  }

  lines.push('} as const;');
  lines.push('');
  lines.push('export type EmbeddedTemplateName = keyof typeof EMBEDDED_TEMPLATES;');
  lines.push('');

  await writeFile(OUTPUT_PATH, lines.join('\n'), 'utf-8');
  console.log(`Embedded ${entries.length} templates → ${path.relative(process.cwd(), OUTPUT_PATH)}`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
